const resultComment = [
  'WATCH NEXT: Nestjs Tutorial: Build Your First App Step-by-Step - <a href="https://www.youtube.com/watch?v=MNa-h_uPNmw">https://youtu.be/MNa-h_uPNmw?si=HzEjSMJcXm_3sAI8</a>',
  "Thanks. :)",
  "AI",
  "Nicely explained! Cheers!<br>Do you get only 5 videos because you had only 5 videos?",
  "thnx, need video how to get oauth2, save and reuse. Can&#39;t update video :(",
  "Very Helpful. I will prefer this video for anyone who want to learn how to fetch data from youTube api.!",
  "I want to upload video can you help ❤",
  "One of the best explanations! But I&#39;m still going crazy trying to find how to get the members-only posts from a channel I&#39;m a member of. 😔 Can anyone help me?",
  "How to retrieve YouTube video views Using npm package With YouTube API??",
  "Thank you so much",
  "Great explanation",
  "Nicely explained. Great !!!<br>👌",
  "thanks alot, that was perfect",
  "Why are you so dead inside",
  "friend you have the Full code?",
  "Excellent video! I have a private video in youtube that I  wana play only in my app the auth take place in my backend and is OK but how to play the protected video?",
  "wow, thank you so much for this amazing tutorial!! really helped me",
  "Nicely explained. Great !!!",
  "Thanks bro awesome",
  "Awesome 🙏🙏",
  "awesome tutorial, I would love to have time stamps so I know everything that&#39;s coveredd",
  "Hello, Oleksandr. You have a great channel for js/web programmers. I&#39;m new to this, I was studying React, applying for jobs a I got an offer to work with SAP Fiori(UI5) as js junior dev. Do you know if it&#39;s a good technology? So far from what I&#39;ve seen I didn&#39;t like the way UI looks, but some functionality that SAPUI5 has is great. Is it worth learning and working with?",
];

[
  "Agree",
  "Neutral",
  "Neutral",
  "Neutral",
  "Agree",
  "Neutral",
  "Neutral",
  "Neutral",
  "Agree",
  "Agree",
  "Agree",
  "Neutral",
  "Neutral",
  "Neutral",
  "Neutral",
  "Agree",
  "Agree",
  "Agree",
  "Agree",
  "Neutral",
  "Neutral",
];
